sudo: required

services:
    - docker

notifications:
    email: false

before_install:
    # Create .splunkrc file with default credentials
    - echo host=localhost >> $HOME/.splunkrc
    - echo username=admin >> $HOME/.splunkrc
    - echo password=changeme >> $HOME/.splunkrc
    # Set SPLUNK_HOME
    - export SPLUNK_HOME="/opt/splunk"
    # Pull docker image
    - docker pull splunk/splunk-sdk-travis-ci:$SPLUNK_VERSION
    # Add DOCKER to iptables, 1/10 times this is needed, force 0 exit status
    - sudo iptables -N DOCKER || true
    # Start Docker container
    - docker run -p 127.0.0.1:8089:8089 -d splunk/splunk-sdk-travis-ci:$SPLUNK_VERSION
    # curl Splunk until it returns valid data indicating it has been setup, try 20 times maximum
    - for i in `seq 0 20`; do if curl --fail -k https://localhost:8089/services/server/info &> /dev/null; then break; fi; echo $i; sleep 1; done


language: node_js
node_js:
    - "6.0"
    - "4.2"
    - "0.12"
    - "0.10"

#Splunk versions can be set here
env:
    - SPLUNK_VERSION=6.6-sdk
    - SPLUNK_VERSION=7.0-sdk

# Test script, should return non 0 exit status if a test fails
script:
    node sdkdo tests
